# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170109_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Szkic')], default=1),
        ),
    ]
